"""
常數定義模組

定義盲水印系統中使用的所有魔術數字與常數
"""

# 圖片處理常數
PIXEL_MAX_VALUE = 255
PIXEL_MIN_VALUE = 0
IMAGE_BINARIZATION_THRESHOLD = 128
WHITE_PIXEL_VALUE = 255
BLACK_PIXEL_VALUE = 0

# 預設分塊尺寸
DEFAULT_BLOCK_HEIGHT = 4
DEFAULT_BLOCK_WIDTH = 4

# 預設魯棒性參數
DEFAULT_ROBUSTNESS_PRIMARY = 36  # d1: 主要奇異值的量化步長
DEFAULT_ROBUSTNESS_SECONDARY = 20  # d2: 次要奇異值的量化步長

# SVD 嵌入參數
SVD_QUANTIZATION_OFFSET = 0.25  # 1/4
SVD_WATERMARK_WEIGHT = 0.5  # 1/2

# 水印權重（用於多通道平均）
PRIMARY_SINGULAR_VALUE_WEIGHT = 3
SECONDARY_SINGULAR_VALUE_WEIGHT = 1
TOTAL_WEIGHT = PRIMARY_SINGULAR_VALUE_WEIGHT + SECONDARY_SINGULAR_VALUE_WEIGHT

# K-means 參數
KMEANS_MAX_ITERATIONS = 300
KMEANS_TOLERANCE = 1e-6

# 縮放搜尋參數
DEFAULT_SCALE_MIN = 0.5
DEFAULT_SCALE_MAX = 2.0
DEFAULT_SEARCH_NUM = 200

# YUV 顏色空間通道數
YUV_CHANNELS = 3

# DWT 小波基
WAVELET_BASIS = 'haar'

# 邊界填充值（YUV 空間）
BORDER_VALUE_Y = 0  # 亮度
BORDER_VALUE_U = 0  # 色度 U
BORDER_VALUE_V = 0  # 色度 V

